Feature/merge all
aws-samples/aws-nitro-enclave-blockchain-wallet pull request #30
Opened 2024-10-01 11:20 UTC by wgr2017

*Issue #, if available:*

*Description of changes:*
Merged all branches, updated README.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-16 13:45 UTC, dpdornseifer requested changes
PR looks good to me - a few minor cleanup tasks required

2024-10-16 13:45 UTC, dpdornseifer commented on aws-nitro-enclave-blockchain-wallet.generated.sln
not required in repo

2024-10-16 13:45 UTC, dpdornseifer commented on application/wireguard/enclave/kms/kmstool_enclave_cli
binary should be removed from repo

2024-10-16 13:45 UTC, dpdornseifer commented on application/wireguard/enclave/kms/libnsm.so
binary should be removed from repo. `.gitignore` should be extended to exclude all `kms` related build artifacts

2024-10-16 13:45 UTC, dpdornseifer commented on application/eth1/enclave/netenclave/obj/project.nuget.cache
merge issue happened / eth1/enclave files are missing `server.py, requirements.txt, Dockerfile`: https://github.com/aws-samples/aws-nitro-enclave-blockchain-wallet/tree/main/application/eth1/enclave

2024-10-16 13:45 UTC, dpdornseifer commented on application/dotnet_sqs_integration/enclave/server.py
> +    print("subprocess args: {}".format(subprocess_args))
print statements inside enclave are not being exposed if debug is turned off

2024-10-16 13:45 UTC, dpdornseifer commented on application/eth1/enclave/netenclave/obj/Debug/net6.0/netenclave.GeneratedMSBuildEditorConfig.editorconfig
debug files should not be included in repo / local path exposed

2024-10-16 13:45 UTC, dpdornseifer commented on application/eth1/enclave/netenclave/obj/netenclave.csproj.nuget.dgspec.json
debug files should not be included in repo / local path exposed / valid for all files in directory

2024-10-16 13:45 UTC, dpdornseifer commented on application/https_web_server/enclave/secure_server.py
> +server.socket = ssl_context.wrap_socket(server.socket, server_side=True)
@wgr2017 ssl version should be fixed to min version >=v1.2

2024-10-16 13:45 UTC, dpdornseifer commented on application/rds_integration/enclave/requirements.txt
psycopg2-binary version pin missing

2024-10-16 13:45 UTC, dpdornseifer commented on application/rds_integration/enclave/server.py
> +    print("subprocess args: {}".format(subprocess_args))
code running inside enclave with no logging capabilities if debug mode turned off

2024-10-16 13:45 UTC, dpdornseifer commented on application/socat/enclave/run_socat.sh
`iperf3` standard invoke should be commented out

2024-10-16 13:45 UTC, dpdornseifer commented on README.md
we should assume `eth1` as default application type and provide a list of all the other options on the central readme.md

2024-11-08 09:20 UTC, wgr2017 commented on application/rds_integration/enclave/requirements.txt
this seems to be missing in the original repo as well

2024-11-08 09:25 UTC, wgr2017 commented on README.md
I believe that is what the current setup is. The central readme.md instructs about the default application type `eth1`, and has links to other readme files.

2024-11-08 09:28 UTC, wgr2017 commented on aws-nitro-enclave-blockchain-wallet.generated.sln
done

2024-11-12 14:15 UTC, dpdornseifer approved these changes
lgtm

2024-11-13 14:30 UTC, merged